### ISSUE TITLE
How to build instruction to readme

### ISSUE THREAD

**Issue by bchtrue** [cyphar/paperback#13]
Hello, I found it at https://privacytoolslist.com but no instruction here or there about how to actually build it and use. is it rust? Possible to add instructions how to quickly setup environment and build it? Thanks

**Comment by cyphar** [comment]
`cargo build` should work out of the box. There are build artifacts uploaded with every commit but GitHub makes it a bit hard to find. I'll mention this in the README.

**Comment by cyphar** [comment]
Fixed in 2509716663a73fb0b4926c661834c0cabfcdc677. I improved some of the CLI prompts to better explain what you need to provide when doing non-backup operations (as well as allowing the user to input the same key shard more than once without having other issues).
