### ISSUE TITLE
Release it as precompiled binary on github

### ISSUE THREAD

**Issue by m040601** [cyphar/paperback#5]
Thanks for your work in this interesting tool.

I haven't yet tried out, but I'm eager to.
Would it be possible to release it as a rust precompiled binary on github ? At least compiled for x86_64 ?

It would make much easier for people who dont have / dont want to download the 500 mega rust distribution just to quickly try it out.

This would also make it easier to provide packages for other linux distros.

Perhaps you can also have a look at how other cli rust tools do it, for example,

skim, https://github.com/lotabout/skim/releases
fd, https://github.com/sharkdp/fd

I assume you are aware of github actions right ?
Have a look at how ripgrep, https://github.com/BurntSushi/ripgrep does it, https://github.com/BurntSushi/ripgrep/tree/master/.github/workflows

Thanks in advance.

**Comment by cyphar** [comment]
I will do that eventually, but the project is still a work-in-progress. The core library code is pretty much done, but I'm still working on a CLI interface you can use to generate the raw form of the documents (with PDF generation coming a bit later when I figure out what crate I need to use). In other words, at the moment there isn't a binary to ship (except maybe an `.rlib` but that won't help you much).

**Comment by cyphar** [comment]
Since ee9f1d89bfc5d98b6b10d28f055213e1e99fed7f we build and upload binaries for several platforms and architectures. It's slightly annoying that artefacts are zipped (and for some reason the amd64 build isn't statically linked) but hopefully this is enough for most people.

**Comment by c33s** [comment]
@cyphar where should i find the downloadable binaries? the releases section here is empty. really would love to try this nice program.

![image](https://user-images.githubusercontent.com/649209/159056575-158eb41b-f29c-4a4e-a3d4-69d3276d8473.png)

**Comment by cyphar** [comment]
There are no releases yet, but you can get the latest builds by going to the latest GitHub Actions run and downloading the zip files there. At the moment that is https://github.com/cyphar/paperback/actions/runs/1744155728.
