### ISSUE TITLE
Unable to Input Complete Single-Line QR Code Data on macOS Terminal

### ISSUE THREAD

**Issue by YouXam** [cyphar/paperback#71]
### Description
On macOS, there appears to be an issue when attempting to input a complete set of QR code data into the terminal in a single line. The macOS terminal input is restricted to 1024 characters as defined by the system limits ([source](https://github.com/apple-oss-distributions/xnu/blob/main/bsd/sys/syslimits.h#L98)). Once 1024 characters have been entered on a single line, any further input (including the Enter key) is not accepted. Typically, the data extracted from QR codes exceeds this 1024-character limit. As a result, this limitation forces users to engage in inconvenient and confusing multiple manual copy-paste operations to input the entire data string.

### Possible Solutions
1. Modify the QR code generation process to output data in multiple lines rather than a single long line. This approach can help users to more easily handle and input data within the limitations of the macOS terminal character count.
2. Explore using libraries like [rustyline](https://github.com/kkawakam/rustyline) which might allow bypassing the 1024 character limit per line. This could provide a more seamless input experience for users dealing with lengthy single-line data.

This issue is particularly critical as the program necessitates the entry of large amounts of data, making it inevitable for macOS users to face this limitation. Users unfamiliar with this system constraint might not understand why they are unable to input data successfully, leading to significant usability concerns. 

We hope this issue can be prioritized for a resolution to enhance the functionality and user experience of macOS terminal operations. Thank you for your attention and looking forward to any updates or feedback from the development team.

**Comment by cyphar** [comment]
Closing this since it should've been a comment in #19, not a new issue.
